return {
  ["workshop-1185229307"]={
    configuration_options={
      CAMERA=true,
      CAPTURE=false,
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      GLOBAL=false,
      GLOBAL_NUMBERS=false,
      HEADER_CLIENT=false,
      HEADER_SERVER=false,
      HORIZONTAL_OFFSET=0,
      TAG="EPIC",
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-2391292843"]={ configuration_options={  }, enabled=true },
  ["workshop-3004733401"]={
    configuration_options={
      ["Sprinkler Item Settings"]=0,
      ["Sprinkler Recipe Settings"]=0,
      SprinklerExtinguishHeatPercent=-1,
      SprinklerFuelBonusMultiplier=5,
      SprinklerMaxFuelTime=250,
      SprinklerProtectionDist=2.25,
      SprinklerProtectionTime=30,
      SprinklerRange=10,
      SprinklerRecipe=2,
      SprinklerTempReduction=5,
      SprinklerWetPlayer="" 
    },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=false,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-569043634"]={
    configuration_options={
      [""]=false,
      Health_Penalty_Campfire="Unchanged",
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Penalty_Skeleton="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      KeepInventory_BugFix="Unchanged",
      KillMe="Unchanged",
      NoPlayerSkeletons="Unchanged",
      RespawnMe="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  } 
}
